pekko {
  actor {
    provider = "cluster"

    serializers {
      jackson-cbor = "org.apache.pekko.serialization.jackson.JacksonCborSerializer"
    }

    serialization-bindings {
      "com.github.galleog.pekko.chapter08b.CborSerializable" = jackson-cbor
    }
  }

  serialization.jackson {
    jackson-modules += "com.fasterxml.jackson.module.kotlin.KotlinModule"
  }

  log-dead-letters = off

  remote {            
    artery {
      transport = tcp
      canonical {
        hostname = 127.0.0.1
        port = 0
      }
    }
  }

  cluster {                 
    seed-nodes = [
     "pekko://WordsCluster@127.0.0.1:2551",
     "pekko://WordsCluster@127.0.0.1:2552",
     "pekko://WordsCluster@127.0.0.1:2553"
    ]

    role {
      seed.min-nr-of-members = 1
      aggregator.min-nr-of-members = 2
    }

    downing-provider-class = "org.apache.pekko.cluster.sbr.SplitBrainResolverProvider"
  }
}

example.countwords {
  workers-per-node = 5
  delegation-parallelism = 20
}
