pekko {
  actor {
    provider = "cluster"               
  } 
  remote {            
    artery {
      transport = tcp
      canonical {
        hostname = 127.0.0.1
        port = ${ARTERY_PORT}
      }
    }
  }

  cluster {                 
    seed-nodes = [
     "pekko://words@127.0.0.1:2551",
     "pekko://words@127.0.0.1:2552",
     "pekko://words@127.0.0.1:2553"
    ]                       

    downing-provider-class = "org.apache.pekko.cluster.sbr.SplitBrainResolverProvider"
  }

  management {
    http {
      hostname = 127.0.0.1
      port = ${MANAGEMENT_PORT}
      route-providers-read-only = false
    }
  }
}
