pekko {
  actor {
    provider = "cluster"

    serializers {
      jackson-cbor = "org.apache.pekko.serialization.jackson.JacksonCborSerializer"
    }

    serialization-bindings {
      "com.github.galleog.pekko.chapter09b.persistence.CborSerializable" = jackson-cbor
    }
  }

  serialization.jackson {
    jackson-modules += "com.fasterxml.jackson.module.kotlin.KotlinModule"
  }

  remote {            
    artery {
      transport = tcp
      canonical {
        hostname = 127.0.0.1
        port = 2551
      }
    }
  }

  cluster {                 
    seed-nodes = [
      "pekko://containers@127.0.0.1:2551"
    ]

    downing-provider-class = "org.apache.pekko.cluster.sbr.SplitBrainResolverProvider"
  }

  persistence {
    journal.plugin = "pekko.persistence.r2dbc.journal"
    snapshot-store.plugin = "pekko.persistence.r2dbc.snapshot"
    state.plugin = "pekko.persistence.r2dbc.state"

    r2dbc {
      dialect = "postgres"
      connection-factory {
        driver = "postgres"
        host = "localhost"
        port = 5432
        database = "containers"
        user = "postgres"
        password = "postgres"
      }
    }
  }
}
