[versions]
kotlin = "1.9.25"
pekko = "1.1.3"
logback = "1.3.14"

[libraries]
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin"}
pekko-bom = { group = "org.apache.pekko", name = "pekko-bom_2.13", version.ref = "pekko" }
logback = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logback" }